# Route for user signin
POST http://localhost:3000/api/signin
Content-Type: application/json

{
    "email":"jean60@example.com",
    "password":"Retraité2023!"
}

###
# Route to filter events
GET http://localhost:3000/api/filterevent


###
# Route to get account details
GET http://localhost:3000/api/myaccount/3


