# Route for user signin
POST http://localhost:3000/api/signin
Content-Type: application/json

{
    "email":"jean60@example.com",
    "password":"Retraité2023!"
}

###
# Route to filter events
GET http://localhost:3000/api/filter-event


###
# Route to get account details
GET http://localhost:3000/api/myaccount/3

###
# Route to update account details
PATCH  http://localhost:3000/api/myaccount/3
Content-Type: application/json

{
    "firstname": "Jean-Claude",
    "picture": "",
    "description": "Amateur de vin blanc.",
    "city":"LYON",
    "smocker": "true",
    "pet": "true",
    "music": "Jazz"
}

###
# Route to delete account details
DELETE  http://localhost:3000/api/myaccount/12
