# Route for user sign in
POST http://localhost:3000/api/signin
Content-Type: application/json

{
    "email":"jean60@example.com",
    "password":"Retraité2023!"
}

###
# Route to filter events
GET http://localhost:3000/api/filter-event


###
# Route to get account details
GET http://localhost:3000/api/myaccount/3


###
# Route to update account details
PATCH  http://localhost:3000/api/myaccount/3
Content-Type: application/json

{
    "firstname": "Jean-Claude",
    "city":"LYON",
    "description": "Amateur de vins.",
    "smoker": "true",
    "pet": "true",
    "music": "Jazz"
}

###
# Route to delete account details
DELETE  http://localhost:3000/api/myaccount/12

### 
# Route to sign up
POST http://localhost:3000/api/signup
Content-Type: application/json

{
    "email": "newuser123@example.com", 
    "password": "NewPassword2023!",
    "repeat_password": "NewPassword2023!",  
    "firstname": "Alice", 
    "gender": "Femme", 
    "gender_match": "Homme", 
    "age": "61", 
    "height": "165",   
    "marital": "Célibataire", 
    "pet": "false",   
    "city": "Lyon",
    "description": "<script></script>j'aime les chats",
    "smoker": "false",
    "music": "variété française",
    "picture":"",
    "zodiac":"poisson",
    "labels": ["Nature", "Culturel"]
}
